Portable config without %appdata%
Twometer/NoFences pull request #44
Opened 2023-11-05 14:02 UTC by maci0

2023-11-15 20:18 UTC, Twometer requested changes
Thanks for the cool contribution! Please see the changes I have requested, then we can merge :-)

2023-11-15 20:18 UTC, Twometer commented on NoFences/Services/FenceManager.cs
> +        private readonly string strExeFilePath = System.Reflection.Assembly.GetExecutingAssembly().Location;
I think this can be a local variable in the constructor

2023-11-15 20:18 UTC, Twometer commented on NoFences/Services/FenceManager.cs
> +            if (Directory.Exists(strExeFilePath + ".portable")){
Please use `Path.Combine()` for the path concatenation

2023-11-18 12:37 UTC, maci0 reviewed
looks good to me

2023-11-30 09:03 UTC, Twometer approved these changes
Looks good to me, but is it intended that you want to merge into the 2.0 branch?

2023-12-01 06:20 UTC, maci0 commented
Yes. Locally I use a version built from the main branch with a similar patch applied. but I assume all new development is gonna happen in the 2.0 branch?

2024-01-17 19:49 UTC, Twometer commented
Yes, the next big version will be 2.0

2024-01-17 19:49 UTC, merged